random_seed:
  value: 27
  description: "Seed for random value"

lr:
  value: 0.01
  description: "Learning rate"

n_hidden_dim:
  value: 16
  description: "Number of hidden units"

epochs:
  value: 200
  description: "Total number of epochs"

dropout_rate:
  value: 0.5
  description: "Dropout rate"

l2_norm:
  value: 0.0001
  description: "L2 normalization"

display_intervals:
  value: 10
  description: "Display training result at every x epoch"